In [1]:
import pandas as pd

embedding = pd.read_csv('/Users/marketdesigners/Documents/GitHub/sentencec-bert/data/embeddings.csv')
embedding

,Dictionary_Entry,Embedding
0,"{'ENTITY': 'a bear with a sore head', 'SUB_TYP...","[0.02475844882428646, 0.0426153838634491, 0.03..."
1,{'ENTITY': 'a bird in the hand is worth two in...,"[0.011406473815441132, 0.032608382403850555, 0..."
2,"{'ENTITY': 'a bit of a dark horse', 'SUB_TYPE'...","[0.033756475895643234, 0.016491426154971123, 0..."
3,"{'ENTITY': 'a bitter pill to swallow', 'SUB_TY...","[-0.008043461479246616, 0.054576851427555084, ..."
4,"{'ENTITY': 'a blessing in disguise', 'SUB_TYPE...","[-0.05557943135499954, 0.13466177880764008, 0...."
...,...,...
14835,"{'ENTITY': 'zone', 'SUB_TYPE': 'vocabulary', '...","[0.17633002996444702, -0.12478479743003845, -0..."
14836,"{'ENTITY': 'zoo', 'SUB_TYPE': 'vocabulary', 'C...","[0.07964568585157394, -0.029255393892526627, 0..."
14837,"{'ENTITY': 'zoologist', 'SUB_TYPE': 'vocabular...","[0.04751398786902428, 0.0318363755941391, 0.01..."
14838,"{'ENTITY': 'zoology', 'SUB_TYPE': 'vocabulary'...","[0.04325025528669357, -0.041528619825839996, 0..."
14839,"{'ENTITY': 'zoom', 'SUB_TYPE': 'vocabulary', '...","[0.05684427544474602, -0.07656628638505936, -0..."